# Generated by Django 3.2.5 on 2021-07-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='alchol',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
