# Generated by Django 3.2.5 on 2021-07-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='comments'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='photo',
            field=models.ImageField(upload_to='postings'),
        ),
    ]
