# Generated by Django 3.2.5 on 2021-10-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='alchol',
        ),
    ]
