# Generated by Django 3.2.5 on 2021-07-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_auto_20210726_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='photo',
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='postings.posting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
