# Generated by Django 3.2.5 on 2021-07-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_auto_20210726_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posting'),
        ),
    ]
