# Generated by Django 3.2.5 on 2021-07-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituent',
            name='reference',
            field=models.URLField(blank=True, null=True),
        ),
    ]
