# Generated by Django 3.2.5 on 2021-10-14 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archives', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constituents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flavortag',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flavor_tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
