# Generated by Django 3.2.5 on 2021-07-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_alter_constituent_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flavortag',
            options={},
        ),
        migrations.RemoveField(
            model_name='constituent',
            name='image',
        ),
        migrations.CreateModel(
            name='ConstituentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='archive_images')),
                ('constituent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituent_images', to='archives.constituent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
