# Generated by Django 3.2.5 on 2021-10-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20211013_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituent',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='flavortag',
            name='expression',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
