# Generated by Django 3.2.5 on 2021-10-09 17:21

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('default', 'default'), ('kakao', 'kakao'), ('naver', 'naver'), ('github', 'github')], default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='static/img/default-profile.jpg', force_format=None, keep_meta=True, quality=-1, size=[170, 170], upload_to='profile_images'),
        ),
    ]
