# Generated by Django 3.2.5 on 2021-08-02 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('postings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customlist',
            name='postings',
            field=models.ManyToManyField(related_name='custom_lists', to='postings.Posting'),
        ),
    ]
